version: "3.9"
services:
  web:
    build: ./docker/web
    volumes:
      - ./backend:/code
    ports:
      - '80:80'

  db:
    build: ./docker/db
    volumes:
      - ./docker/db/data:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cotwo
      - MYSQL_USER=django
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
  
  redis:
    build: ./docker/redis
    ports:
      - '6379:6379'

  memcached:
    image: memcached:latest
    ports:
      - '11211:11211'
      
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: supervisord
    volumes:
      - ./backend:/code
    expose:
      - '8001'
      - '8002'

  daemon:
    build:
      context: .
      dockerfile: ./docker/daemon/Dockerfile
    volumes:
      - ./daemon:/code
    command: python dummy.py
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/code
