version: "3.9"
services:
  web:
    build: ./docker/web
    ports:
      - '80:80'
    volumes:
      - ./backend:/code

  db:
    build: ./docker/db
    env_file: ./docker/db/mariadb.env
    volumes:
      - ./docker/db/data:/var/lib/mysql
    expose:
      - '3306'

  # Django REST framwork
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: uwsgi --socket :8001 --module config.wsgi
    volumes:
      - ./backend:/code
    expose:
      - '8001'

  daemon:
    build:
      context: .
      dockerfile: ./docker/daemon/Dockerfile
    volumes:
      - ./daemon:/code
    tty: true

  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/code
